#     -DLIBASSERT_USE_MAGIC_ENUM=ON
cmake .. \
    -GNinja \
    -DLIBASSERT_BUILD_TESTING=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_INSTALL_PREFIX=install \
    -DLIBASSERT_USE_EXTERNAL_CPPTRACE=ON


