context:
  version: "2.1.3"

package:
  name: libassert
  version: ${{ version }}

source:
  git: https://github.com/jeremy-rifkin/libassert.git
  tag: v${{ version }}

build:
  number: 1000

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - cpptrace
    # - magic_enum

tests:
  - package_contents:
      include:
        - libassert/assert.hpp
      lib:
        - libassert.so
about:
  homepage: https://github.com/jeremy-rifkin/libassert.git
  license: MIT
  license_file: LICENSE
  summary: The most over-engineered C++ assertion library
  description: Library philosophy Provide as much helpful diagnostic info as possible.
